### ISSUE TITLE
typescript issues

### ISSUE THREAD

**Issue by surfjedi** [steveblue/ngus#2]
Awesome for coming up with this!

I have come across some typescript errors - the first I fixed and already put up a quick PR, but now there's more:

app.ts(66,12): error TS2339: Property 'famousComponent' does not exist on type 'App'.
app.ts(80,12): error TS2339: Property 'angularComponent' does not exist on type 'App'.
ngus/core/dom-element.ts(29,22): error TS2304: Cannot find name 'famous'.
ngus/core/dom-element.ts(38,33): error TS2339: Property 'setContent' does not exist on type 'Object'.
ngus/core/dom-element.ts(42,27): error TS2339: Property 'setProperty' does not exist on type 'Object'.
ngus/core/node.ts(50,37): error TS2339: Property 'addChild' does not exist on type 'Object'.
ngus/core/node.ts(55,15): error TS2339: Property 'setMountPoint' does not exist on type 'Object'.
ngus/core/node.ts(60,15): error TS2339: Property 'setOrigin' does not exist on type 'Object'.
ngus/core/node.ts(65,15): error TS2339: Property 'setAlign' does not exist on type 'Object'.
ngus/core/node.ts(69,15): error TS2339: Property 'setPosition' does not exist on type 'Object'.
ngus/core/node.ts(73,15): error TS2339: Property 'setRotation' does not exist on type 'Object'.
ngus/core/node.ts(77,15): error TS2339: Property 'setScale' does not exist on type 'Object'.
ngus/core/node.ts(81,15): error TS2339: Property 'setSizeMode' does not exist on type 'Object'.
ngus/core/node.ts(85,15): error TS2339: Property 'setAbsoluteSize' does not exist on type 'Object'.
ngus/core/node.ts(89,15): error TS2339: Property 'setProportionalSize' does not exist on type 'Object'.
ngus/core/node.ts(93,15): error TS2339: Property 'setDifferentialSize' does not exist on type 'Object'.
ngus/core/node.ts(97,15): error TS2339: Property 'setOpacity' does not exist on type 'Object'.
ngus/core/node.ts(114,35): error TS2339: Property 'addComponent' does not exist on type 'Object'.
ngus/service/famous.ts(18,34): error TS2339: Property 'createScene' does not exist on type 'Object'.
ngus/service/famous.ts(19,21): error TS2339: Property 'init' does not exist on type 'Object'.
ngus/webgl-renderables/mesh.ts(28,16): error TS2304: Cannot find name 'famous'.
ngus/webgl-renderables/mesh.ts(33,17): error TS2304: Cannot find name 'famous'.
ngus/webgl-renderables/mesh.ts(34,31): error TS2339: Property 'setGeometry' does not exist on type 'Object'.
ngus/webgl-renderables/mesh.ts(34,70): error TS2339: Property 'setGeometry' does not exist on type 'Object'.
ngus/webgl-renderables/mesh.ts(35,28): error TS2339: Property 'setBaseColor' does not exist on type 'Object'.
ngus/webgl-renderables/mesh.ts(35,76): error TS2339: Property 'setBaseColor' does not exist on type 'Object'.

**Comment by surfjedi** [comment]
And also can't run off the bat with the following errors, is there some code missing from the intial commit?

![ngus_demo](https://cloud.githubusercontent.com/assets/536809/9078630/0ee3811c-3afe-11e5-88be-9f441ab33db5.png)

**Comment by steveblue** [comment]
@surfjedi the code that was timing out for you was hosted on jspm, which occasionally has an outage. I localized these files to the /bundle folder so this will not happen again. Also, you see these errors in typescript b/c there are no definitions written for Famo.us Engine yet. Still very early in development, someone needs to contribute typescript definitions. Update your fork from master.

**Comment by steveblue** [comment]
@surfjedi I fixed all warnings coming from the typescript compiler.

**Comment by surfjedi** [comment]
Sweet!
